version: '3.7'
services:
  database:
    container_name: db.primebuy
    image: postgres:11
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.2'
          memory: 1024M
